layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/
google_analytics: G-DS2J0ZVN1K
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: false
    projects:
      # name

social_media:
  # behance: your_username
  # dribbble: your_username
  facebook: sihao.benny.chen
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: sihaochen
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

# topics:
#   - name: Reinforcement Learning
#     web_url: https://github.com/topics/reinforcement-learning

#   - name: Machine Learning
#     web_url: https://github.com/topics/machine-learning

#   - name: Robotics
#     web_url: https://github.com/topics/robotics
    # image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/sass/sass.png
